controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_velocity_controller:
  ros__parameters:
    joints:
      - rl_wheel_joint
      - rr_wheel_joint      
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

forward_position_controller:
  ros__parameters:
    joints:
      - front_left_knuckle_joint
      - front_right_knuckle_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
